const express = require("express");
const marcas = require("./../routes/marcas");
const tipos = require("./../routes/tipos");
const carros = require("./../routes/carros");
const alugueis = require("./../routes/alugueis");
const returns = require("./../routes/returns");
const register = require("./../routes/register");
const login = require("./../routes/login");
const users = require("./../routes/users");
const error = require("./../middleware/error");
module.exports = function (app) {
  app.use(express.json());
  app.use("/marcas", marcas);
  app.use("/tipos", tipos);
  app.use("/carros", carros);
  app.use("/alugueis", alugueis);
  app.use("/returns", returns);
  app.use("/register", register);
  app.use("/login", login);
  app.use("/users", users);
  app.use(error);
};
